### ISSUE TITLE
DatabaseReader constructor yields an exception on .Net Core / Windows 8.1

### ISSUE THREAD

**Issue by flo8** [maxmind/GeoIP2-dotnet#74] opened 2017-02-12 21:07 UTC
Hi,
I got a strange behavior with the DatabaseReader constructor with .Net Core on Windows 8.1. The mmdb does exist but I get a FileNotFoundException. When writing the *very exact* same code on a .Net 4.6 C# app, it loads without any problem. Any idea why?
![problem](https://cloud.githubusercontent.com/assets/2037837/22865986/b1dafb16-f16e-11e6-90a7-6662e33a7fa1.png)

**Comment by oschwald** [comment] 2017-02-14 16:15
That is pretty weird. Is there anything unusual about the database you are trying to load? For instance, is it on a network drive?

**Comment by flo8** [comment] 2017-02-14 20:03
There was nothing unusual. The only thing I can think of is that this function is not executed on the main thread of the app.. However it is very weird that the very same program in .Net 4.6 running on the same machine, at the same time, with the same file, works without any problem?
I also found that if I use the constructor with the FileAccessMode.Memory then it works (even in the child thread).

**Comment by oschwald** [comment] 2017-02-21 16:02
Do our tests run fine for you? They should use the constructor in the same way. Would it be possible for you to create a small test solution that demonstrates the issue?

**Comment by solenwin2** [comment] 2017-10-02 02:56
test run fine issue.

**Comment by coderb** [comment] 2018-05-29 14:57
FYI.... hah!  the issue is a red herring.  the exception happens internal to the MMF code in the dotnet base libraries and is caught and handled.  The code works fine!  I got confused (like the author) due to my default setting of "break on all exceptions" inside the debugger.

**Comment by oschwald** [comment] 2018-06-05 21:42
@coderb, thanks for the explanation. That makes sense. @flo8, does that explain what you were seeing or do you still have problems with the "break on all exceptions" option disabled?

**Comment by oschwald** [comment] 2019-07-03 22:12
Based on the last comment, I am going to close this issue. I am happy to reopen it if there is an indication that it is not a red herring.

**Closed by oschwald** 2019-07-03 22:12 UTC
