### ISSUE TITLE
Issue with client.City(IP)

### ISSUE THREAD

**Issue by dgarcia4598** [maxmind/GeoIP2-dotnet#319] opened 2024-09-05 16:44 UTC
I'm getting this error message "MaxMind.GeoIP2.Exceptions.GeoIP2Exception: 'Received a 200 response but not decode it as JSON'"

This is my code and I'm using the nugget package MaxMind.GeoIP2 Version 5.2

```
using (var client = new MaxMind.GeoIP2.WebServiceClient(maxmindAccountID, maxmindAPIKey))
{
     var response = client.City(IP); -- "here I get the exception"
     return response;
}

```
FYI use the same IP with a webservice call using this ("https://geoip.maxmind.com/geoip/v2.1/city/{ip_address}") and I get response with the correct information...

**Comment by oschwald** [comment] 2024-09-05 16:54
I suggest contacting support@maxmind.com or using the chat on the website. They will be able to look into the request in more detail and debug the issue with you. These sorts of issues are often caused by a proxy.

**Comment by dgarcia4598** [comment] 2024-09-05 16:56
@oschwald thanks for your suggestion, I will do it!

**Comment by oschwald** [comment] 2024-09-05 18:46
I'll close this as it sounds like you talked to support and figured out the problem.

**Closed by oschwald** 2024-09-05 18:46 UTC
